version: '3.8'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8010:8000"
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: appointmentsystem
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    tty: true

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    command: celery -A config worker --loglevel=info
    volumes:
      - ./backend:/code
    depends_on:
      - db
      - redis


volumes:
  postgres_data:
  ollama_data:
