# Generated by Django 4.2.20 on 2025-04-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonannouncement',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lessonannouncement',
            name='student_class_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lessonannouncement',
            name='student_request_detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonannouncement',
            name='student_requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonannouncement',
            name='student_requested_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
