# Generated by Django 4.2.20 on 2025-04-13 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lesson'),
        ),
    ]
