# Generated by Django 4.2.20 on 2025-04-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_lessonannouncement_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonannouncement',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.lesson'),
        ),
    ]
