# Generated by Django 4.2.20 on 2025-04-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_teacher_expertise_area_teacher_graduated_school_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
