# Generated by Django 4.2.20 on 2025-04-27 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_lessonannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonannouncement',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
    ]
